### ISSUE TITLE
Server crashes due to timeout of connection?

### ISSUE THREAD

**Issue by ThomasTNO** [TNO-S3/Dummy-HTTP-Server#5]
After a while the server can show crashing behaviour. Possibly due to some timeouts?

Hard to reproduce reliably panic:
```
thread 'main' panicked at src/main.rs:66:45:
index out of bounds: the len is 0 but the index is 0
```

**Comment by ThomasTNO** [comment]
Backtrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:274:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/slice/index.rs:248:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/slice/index.rs:17:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/vec/mod.rs:2905:9
   6: dummy_http_server::handle_connection
             at ./src/main.rs:66:45
   7: dummy_http_server::main
             at ./src/main.rs:30:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
